--
--Script to create database schema for disaster relief management.
--
--Major stakeholder entities
----------------------------
--Donors - Entities (local/overseas) that donate items as aid for victims of disaster
--Collectors - Entities that collect/receive aid from donor entities
--Distributors - Entities designated for distribution of aid to victims of disaster
--
--Database schema
----------------------------
--
--Extensions
--
create extension citext;

--
--Country table
--
create table country
(
	country_id smallint not null
		constraint pk_country primary key,
	country_name varchar(80) not null
);
--
--Country table
--
create table parish
(
	parish_code char(2) not null
		constraint c_parish_1 check (parish_code similar to '[0-9]*' and parish_code::integer between 1 and 14)
		constraint pk_parish primary key,
	parish_name varchar(40) not null
);
--
--Event for which donations are received
--
create table event
(
	event_id integer not null generated by default as identity
		constraint pk_event primary key,
		
	event_type varchar(16) not null
		constraint c_event_1 check
		(event_type in ('STORM','TORNADO','FLOOD','TSUNAMI','FIRE','EARTHQUAKE','WAR','EPIDEMIC')),

	start_date date not null		
		constraint c_event_2 check (start_date <= CURRENT_DATE),

	--Name (universal/local) assigned to event.
	event_name varchar(60) not null,
	
	--Description of event
	event_desc varchar(255) not null,

	--Description of impact of event. Should provide a utility for formatted text.
	impact_desc text not null,

	status_code char(1) not null
		--A=Active, C=Closed
		constraint c_event_3 check (status_code in ('A','C')),
	closed_date date
		constraint c_event_4a
		check ((status_code = 'A' and closed_date is null)
			or (status_code = 'C' and closed_date is not null)),
	reason_desc varchar(255)
		constraint c_event_4b
		check ((reason_desc is null and closed_date is null)
			or (reason_desc is not null and closed_date is not null)),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);
--
--Donor entities - individuals and organizations
--
create table donor
(
	donor_id integer not null generated by default as identity
		constraint pk_donor primary key,
		
	donor_type char(1) not null
		--I=Individul, O=Organization
		constraint c_donor_1 check (donor_type in ('I','O')),
		
	donor_name varchar(255) not null
		--Donor name must be uppercase and unique
		constraint c_donor_2 check (donor_name = upper(donor_name))
		constraint uk_donor_1 unique,
		
	--Short description of organization type e.g. Church, Bank, International Aid, Lion's Club, etc.
	--Can be used for analysis of inventory by categories of organizations
	org_type_desc varchar(30),
	
	address1_text varchar(255) not null,
	address2_text varchar(255),
	--Indicate country in which donor is located, default is Jamaica
	country_id smallint not null default 388 
		constraint fk_donor_country references country,
		
	phone_no varchar(20) not null,
	email_text varchar(100),
	
	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);

--
--GOJ agency having custody for warehouses - ODPEM. Custodian collect donation,
--receive items in warehouses (relief stores), transfer between warehouses, 
--dispatch from warehouses to outposts (distribution points)
--
create table custodian
(
	custodian_id integer not null generated by default as identity
		constraint pk_custodian primary key,
	
	custodian_name varchar(120) not null
		default 'OFFICE OF DISASTER PREPAREDNESS AND EMERGENCY MANAGEMENT (ODPEM)'
		--custodian name must be uppercase and unique
		constraint c_custodian_1 check (custodian_name = upper(custodian_name))
		constraint uk_custodian_1 unique,
	
	address1_text varchar(255) not null,
	address2_text varchar(255),
	--Indicate parish in which custodian is located
	parish_code char(2) not null
		constraint fk_custodian_parish references parish,
	
	contact_name varchar(50) not null
		--Contact name must be in upper case.
		constraint c_custodian_3 check (contact_name = upper(contact_name)),
	phone_no varchar(20) not null,
	email_text varchar(100),
	
	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);

--
--Units in which relief item quantity is measured (units of measure (UOM))
--Should be presented for selected as a dropdown list containing among other entries:
--USD, JMD, PERSONS, KILOGRAMS, GALLONS, SACKS, BOTTLES, BOXES, METERS, UNITS,
--10-FOOT SHEETS, 5-GALLON BOTTLES, 30X50 FEET, etc.
--
create table unitofmeasure 
(
	uom_code varchar(25) not null
		constraint c_unitofmeasure_1 check (uom_code = upper(uom_code))
		constraint pk_unitofmeasure primary key,

	--Description of unit of measure
	uom_desc varchar(60) not null,

	--Any comments related to this unit of measure
	comments_text text,

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);

--
--Item types - Category in which item is classified
--Should be presented for selected as a dropdown list containing among other entries:
--Type of item (MONEY, MEDICAL SUPPLIES, CONSTRUCTION MATERIAL, FOOD ITEM, CLOTHING,
--WATER, FURNITURE, BED MATERIALS, MEDICAL DOCTORS, ENGINEERS, etc.)
--
create table itemcatg 
(
	category_code varchar(30) not null
		constraint c_itemcatg_1 check (category_code = upper(category_code))
		constraint pk_category_code primary key,

	--Description of item category
	category_desc varchar(60) not null,

	--Any comments related to this item type
	comments_text text,

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);

--
--Relief items e.g. mattresses, tarpaulin, flour, rice, etc.
--
create table item
(
	item_id integer not null generated by default as identity
		constraint pk_item primary key,

	item_name varchar(60) not null
		--Item name must be uppercase and unique
		constraint c_item_1a check (item_name = upper(item_name))
		constraint uk_item_1 unique,

	sku_code varchar(30) not null
		constraint c_item_1b check (sku_code = upper(sku_code))
		constraint uk_item_2 unique,

	--Category of item
	category_code varchar(30) not null
		constraint fk_item_itemcatg references itemcatg,

	--Details of item properties/characteristics. Stored as case insensitive text.
	item_desc citext not null,

	--Minimum quantity of item at which re-order is required
	reorder_qty decimal(12,2) not null
		constraint c_item_1c check (reorder_qty > 0.00),
	
	--Type of units in which item quantity is measured by default (units of measure (UOM)).
	default_uom_code varchar(25) not null
		constraint fk_item_unitofmeasure references unitofmeasure,

	--Description of any specification re: how/where item should be used/operated
	usage_desc text,

	--Description of any specification re: how/where item should be stored
	storage_desc text,

	--Does expiration apply to use of item? If true, item must not be disbursed if expired.
	expiration_apply_flag boolean not null,

	--Any comments related to this item
	comments_text text,
	
	status_code char(1) not null
		--A=Active, I=Inactive
		constraint c_item_2 check (status_code in ('A','I'))

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);
--Create index on description to allow for filtering on items to be in dropdown list
create index dk_item_1 on item(item_desc);

--
--Records of donations received
--
create table donation
(
	donation_id integer not null generated by default as identity
		constraint pk_donation primary key,

	--Donor and description of donation received
	donor_id integer not null
		constraint fk_donation_donor references donor,
	donation_desc text not null,

	--Event for which donation was made
	event_id integer not null
		constraint fk_donation_event references event,
	
	--Agency that collected donation and date of collection
	custodian_id integer not null
		constraint fk_donation_custodian references custodian,
	received_date date not null
		constraint c_donation_1 check (received_date <= CURRENT_DATE),

	status_code char(1) not null
		--E=Entered, V=Verified
		constraint c_donation_2 check (status_code in ('E','V')),

	--Any comments related to the receipt of donation
	comments_text text,

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	verify_by_id varchar(20) not null,
	verify_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);		
--
--Items contained in donation
--
create table donation_item
(
	donation_id integer not null
		constraint fk_donation_item_donation references donation,
	item_id integer not null
		constraint fk_donation_item_item references item,
	
	--Quantity/amount of items received
	item_qty decimal(12,2) not null
		constraint c_donation_item_1 check (item_qty >= 0.00),

	--Actual units in which quantity of item received is measured. Note that quantity
	--of the item received may be measured in a different unit from the designated
	--default unit of measure.
	uom_code varchar(25) not null
		constraint fk_donation_item_unitofmeasure references unitofmeasure,

	--Place at which consignment is located (bank, address, name of entity)
	location_name text not null,

	status_code char(1) not null
		--P=Pending verification, V=Verified
		constraint c_donation_item_2 check (status_code in ('P','V')),

	--Any comments on item donated
	comments_text text,
		
	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	verify_by_id varchar(20) not null,
	verify_dtime timestamp(0) without time zone not null,
	version_nbr integer not null,

	constraint pk_donation_item primary key(donation_id,item_id)
);		

--
--Warehouses storing relief items
--
create table warehouse
(
	warehouse_id integer not null generated by default as identity
		constraint pk_warehouse primary key,

	--Name of warehouse e.g. Darliston warehouse, Maroon Town warehouse, etc.
	warehouse_name text not null,

	warehouse_type varchar(10) not null
		constraint c_warehouse_1 check (warehouse_type in ('MAIN','HUB','SUB-HUB','AGENCY')),

	address1_text varchar(255) not null,
	address2_text varchar(255),
	--Indicate parish in which warehouse is located
	parish_code char(2) not null
		constraint fk_warehouse_parish references parish,

	contact_name varchar(50) not null
		--Contact name must be in upper case.
		constraint c_warehouse_2 check (contact_name = upper(contact_name)),
	phone_no varchar(20) not null,
	email_text varchar(100),

	--Identifier for GOJ entity (ODPEM) with responsibility for warehouse's operation
	custodian_id integer not null
		constraint fk_warehouse_custodian references custodian,

	status_code char(1) not null
		constraint c_warehouse_3 check (status_code in ('A','I')),
	reason_desc varchar(255)
		constraint c_warehouse_4
		check ((reason_desc is null and status_code = 'A')
			or (reason_desc is not null and status_code = 'I')),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);

--
--Items contained in warehouse inventory. Items may be obtained 
--from multiple events (disaster relief, poor relief, etc.)
--
create table inventory
(
	inventory_id integer not null generated by default as identity
		constraint pk_inventory primary key,
	warehouse_id integer not null
		constraint fk_inventory_warehouse references warehouse,
	item_id integer not null
		constraint fk_inventory_item references item,

	--Quantity/amount of usable/good item in inventory
	usable_qty decimal(12,2) not null
		constraint c_inventory_1 check (usable_qty >= 0.00),
	
	--Quantity/amount of item reserved/blocked for one/more distributions
	reserved_qty decimal(12,2) not null
		constraint c_inventory_2 check (reserved_qty <= usable_qty),
	
	--Quantity/amount of defective item in inventory
	defective_qty decimal(12,2) not null
		constraint c_inventory_3 check (defective_qty >= 0.00),
	
	--Quantity/amount of expired item in inventory
	expired_qty decimal(12,2) not null
		constraint c_inventory_4 check (defective_qty >= 0.00),

	--Units in which quantity of item is measured
	uom_code varchar(25) not null
		constraint fk_inventory_unitofmeasure references unitofmeasure,
	
	last_verified_by varchar(20),
	Last_verified_date date
		constraint c_inventory_5
		check ((last_verified_by is null and Last_verified_date is null)
			or (last_verified_by is not null and Last_verified_date is not null)),

	status_code char(1) not null
		--A=Available, U=Unavailable
		constraint c_inventory_6 check (status_code in ('A','U')),

	--Any comments on item in inventory
	comments_text text,
		
	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);
--Create unique index to present items in a given inventory & items across
--all inventories where inventory is not given
create unique index uk_inventory_1 on inventory(item_id, inventory_id);
--Create duplicate index on inventory to optimize join with warehouse.
create index dk_inventory_1 on inventory(warehouse_id);
--Index for checking if there is any of a usable item across inventory
create unique index uk_inventory_2 on inventory(item_id) where usable_qty > 0.00;


--
--Location(s) of items in inventory.
--
create table location
(
	location_id integer not null generated by default as identity
		constraint pk_location primary key,
	inventory_id integer not null
		constraint fk_location_inventory references inventory,
	location_desc varchar(255) not null,
	status_code char(1) not null
		--Re operations, status can be: O=Open, C=Closed
		constraint c_location_1 check (status_code in ('O','C')),
	comments_text varchar(255),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);
--Duplicate key to retrieve all locations in inventory
create index dk_location_1 on location(inventory_id);

--Location of item in inventory. Inventory is repeated on this table for join with
--inventory without going through location, and enforcement of integrity relations
create table item_location
(
	inventory_id integer not null,
	item_id integer not null,
	location_id integer not null
		constraint fk_item_location_location references location,
	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,

	--Constraint to ensure item at location exists in inventory
	constraint fk_item_location_inventory foreign key(item_id, inventory_id)
		references inventory(item_id, inventory_id),
	constraint pk_item_location primary key(item_id, location_id)
);
--Duplicate key on inventory and location to get all locations in inventory
create index dk_item_location_1 on item_location(inventory_id, location_id);

--
--Record of intake of donations/consignment to inventory
--During intake, items are inspected and classified as usable/defective
--and assigned to required locations.
--
create table dnintake
(
	donation_id integer not null
		constraint fk_dnintake_donation references donation,
	inventory_id integer not null
		constraint fk_dnintake_inventory references inventory,
	intake_date date not null
		constraint c_dnintake_1 check (intake_date <= CURRENT_DATE),
	comments_text varchar(255),

	status_code char(1) not null
		--I=Incomplete, C=Completed, V=Verified
		constraint c_dnintake_2 check (status_code in ('I','C','V')),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone,
	verify_by_id varchar(20) not null,
	verify_dtime timestamp(0) without time zone,
	version_nbr integer not null,
	constraint pk_dnintake primary key(donation_id,inventory_id)
);

--Intake items from donation/return to inventory. Assignment of items to locations is
--optional.
--NOTE: Intake of items from a donation must not reference inventory as items being
--taken to the inventory may not yet exist in it.
create table dnintake_item
(
	donation_id integer not null,
	inventory_id integer not null,
	item_id integer not null,

	--Quantity/amount of usable/good item in inventory
	usable_qty decimal(12,2) not null
		constraint c_dnintake_item_1 check (usable_qty >= 0.00),
	location1_id integer --not null
		constraint fk_dnintake_item_location1 references location,
	
	--Quantity/amount of defective item in inventory
	defective_qty decimal(12,2) not null
		constraint c_dnintake_item_3 check (defective_qty >= 0.00),
	location2_id integer --not null
		constraint fk_dnintake_item_location2 references location,
	
	--Quantity/amount of expired item in inventory
	expired_qty decimal(12,2) not null
		constraint c_dnintake_item_4 check (defective_qty >= 0.00),
	location3_id integer --not null
		constraint fk_dnintake_item_location3 references location,

	--Units in which quantity of item is measured
	uom_code varchar(25) not null
		constraint fk_dnintake_item_unitofmeasure references unitofmeasure,


	status_code char(1) not null
		--P=Pending verification, V=Verified
		constraint c_dnintake_item_5 check (status_code in ('P','V')),
	comments_text varchar(255),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null,

	constraint fk_dnintake_item_intake foreign key (donation_id,inventory_id) 
		references dnintake(donation_id,inventory_id),
	constraint fk_dnintake_item_donation_item foreign key(donation_id,item_id)
		references donation_item(donation_id,item_id),
	constraint pk_dnintake_item primary key(donation_id,inventory_id,item_id)
);
create index dk_dnintake_item_1 on dnintake_item(inventory_id, item_id);
create index dk_dnintake_item_2 on dnintake_item(item_id);

--
--Record of transfers of items to another inventory
--
create table transfer
(
	transfer_id integer not null generated by default as identity
		constraint pk_transfer primary key,

	--Inventories involved in transfer.
	fr_inventory_id integer not null
		constraint fk_transfer_inventory1 references inventory,
	to_inventory_id integer not null
		constraint fk_transfer_inventory2 references inventory,

	transfer_date date not null default CURRENT_DATE
		constraint c_transfer_1 check (transfer_date <= CURRENT_DATE),

	--Reason for transfer
	reason_text varchar(255),

	status_code char(1) not null
		--Status of transfer transaction: D=Draft, C=Completed, V=Verified
		constraint c_transfer_2 check (status_code in ('D','C','V')),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone,
	verify_by_id varchar(20) not null,
	verify_dtime timestamp(0) without time zone,
	version_nbr integer not null
);
--Indexes to retrieve transfer by date, source and destination Inventories
create index dk_transfer_1 on transfer(transfer_date);
create index dk_transfer_2 on transfer(fr_inventory_id);
create index dk_transfer_3 on transfer(to_inventory_id);

--Assumption: Only usable items will be transferred. The quantity available for transfer is
--the item's usable quantity minus the reserved quantity. Verification of a transfer must reduce
--the usable quantity by the quantity transferred, and increment the reserved quantity by the same
--quantity.
create table transfer_item
(
	transfer_id integer not null
		constraint fk_transfer_item_transfer references transfer,
	--Inventory from which items are to be transferred
	inventory_id integer not null,
	item_id integer not null,

	--Quantity/amount of item transferred
	item_qty decimal(12,2) not null
		constraint c_transfer_item_1 check (item_qty >= 0.00),

	--Units in which quantity of item is measured
	uom_code varchar(25) not null
		constraint fk_transfer_item_unitofmeasure references unitofmeasure,

	reason_text varchar(255),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null,
	constraint fk_transfer_item_inventory foreign key(item_id, inventory_id) references inventory(item_id, inventory_id),
	constraint pk_transfer_item primary key(transfer_id,item_id)
);

--
--Record of intake of items transferred to inventory
--During intake, items are inspected and classified as usable/defective
--and assigned to required locations.
--
create table xfintake
(
	transfer_id integer not null
		constraint fk_xfintake_transfer references transfer,

	inventory_id integer not null
		constraint fk_xfintake_inventory references inventory,

	intake_date date not null
		constraint c_xfintake_1 check (intake_date <= CURRENT_DATE),
	comments_text varchar(255),

	status_code char(1) not null
		--I=Incomplete, C=Completed, V=Verified
		constraint c_xfintake_2 check (status_code in ('I','C','V')),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone,
	verify_by_id varchar(20) not null,
	verify_dtime timestamp(0) without time zone,

--NOTE: Intake of items must not reference inventory as items being taken to the
--inventory may not yet exist in it.	version_nbr integer not null
	constraint pk_xfintake primary key(transfer_id,inventory_id)
);

--Intake of items from transfer to inventory. The number of items taken into inventory
--must be equal to the number in the transfer transaction. Assignment of items to
--locations is optional.
--NOTE: Intake of items from a transfer must not reference inventory as items being
--taken to the inventory may not yet exist in it.

create table xfintake_item
(
	transfer_id integer not null,
	inventory_id integer not null,
	item_id integer not null,

	--Quantity/amount of usable/good item in inventory
	usable_qty decimal(12,2) not null
		constraint c_xfintake_item_1 check (usable_qty >= 0.00),
	location1_id integer --not null
		constraint fk_xfintake_item_location1 references location,
	
	--Quantity/amount of defective item in inventory
	defective_qty decimal(12,2) not null
		constraint c_xfintake_item_2 check (defective_qty >= 0.00),
	location2_id integer --not null
		constraint fk_xfintake_item_location2 references location,
	
	--Quantity/amount of expired item in inventory
	expired_qty decimal(12,2) not null
		constraint c_xfintake_item_3 check (defective_qty >= 0.00),
	location3_id integer --not null
		constraint fk_xfintake_item_location3 references location,

	--Units in which quantity of item is measured
	uom_code varchar(25) not null
		constraint fk_xfintake_item_unitofmeasure references unitofmeasure,

	status_code char(1) not null
		--P=Pending verification, V=Verified
		constraint c_xfintake_item_4 check (status_code in ('P','V')),
	comments_text varchar(255),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null,

	constraint fk_xfintake_item_intake foreign key (transfer_id,inventory_id) 
		references xfintake(transfer_id,inventory_id),
	constraint pk_xfintake_item primary key(transfer_id,inventory_id,item_id)
);
create index dk_xfintake_item_1 on xfintake_item(inventory_id, item_id);
create index dk_xfintake_item_2 on xfintake_item(item_id);

--
--Record of returns of items transferred to inventory. Items returned must
--have previously transferred to the returning inventory. Items returned may
--originate from multiple transfers previously done.
--During receipt of returns, items are inspected and classified as usable or
--defective and assigned to required locations.
--Reason for returns is required.
--
create table xfreturn
(
	xfreturn_id integer not null generated by default as identity
		constraint pk_xfreturn primary key,

	--Inventories involved in items returned.
	fr_inventory_id integer not null
		constraint fk_xfreturn_inventory1 references inventory,
	to_inventory_id integer not null
		constraint fk_xfreturn_inventory2 references inventory,

	return_date date not null default CURRENT_DATE
		constraint c_xfreturn_1 check (return_date <= CURRENT_DATE),

	--Reason for return
	reason_text varchar(255),

	status_code char(1) not null
		--Status of returned items transaction: D=Draft, C=Completed, V=Verified
		constraint c_xfreturn_2 check (status_code in ('D','C','V')),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone,
	verify_by_id varchar(20) not null,
	verify_dtime timestamp(0) without time zone,
	version_nbr integer not null
);
--Indexes to retrieve transfer by date, source and destination Inventories
create index dk_xfreturn_1 on xfreturn(return_date);
create index dk_xfreturn_2 on xfreturn(fr_inventory_id);
create index dk_xfreturn_3 on xfreturn(to_inventory_id);

--Assumption: All categories of items can be returned (usable, defective, expired).
--The item quantities available for return must be less than the corresponding item quantity
--excepting where the usable quantity to return must be less than the usable quantity minus
--the reserved quantity. Verification of a return must reduce the usable quantity by the
--corresponding quantity to return, and increment the reserved quantity by the same quantity.
--For quantities pertaining to defective and expired items, the inventory quantity must be
--reduced by the quantity to return.

create table xfreturn_item
(
	xfreturn_id integer not null
		constraint fk_xfreturn_item_xfreturn references xfreturn,
	--Inventory from which items are to be returned
	inventory_id integer not null,
	item_id integer not null,

	--Quantities/amounts of items returned

	usable_qty decimal(12,2) not null
		constraint c_xfreturn_item_1 check (usable_qty >= 0.00),

	defective_qty decimal(12,2) not null
		constraint c_xfreturn_item_2 check (defective_qty >= 0.00),

	expired_qty decimal(12,2) not null
		constraint c_xfreturn_item_3 check (expired_qty >= 0.00),

	--Units in which quantity of item is measured
	uom_code varchar(25) not null
		constraint fk_xfreturn_item_unitofmeasure references unitofmeasure,

	reason_text varchar(255),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null,
	constraint fk_xfreturn_item_inventory foreign key(item_id, inventory_id) references inventory(item_id, inventory_id),
	constraint pk_xfreturn_item primary key(xfreturn_id,inventory_id,item_id)
);

--
--Record of intake of returned items previously transferred from inventory.
--Items returned are classified as usable, defective and expired.
--This is done to ensure that the corresponding quantities in the source
--inventory are updated with the quantities returned.
--The quantities for each category of items may be changed on intake inspection
--but the total items taken in (i.e. usable + defective + expired) must be
--the same as the total quantity returned.
--Items taken in can be assigned to required locations.
--
create table rtintake
(
	xfreturn_id integer not null
		constraint fk_rtintake_xfreturn references xfreturn,

	inventory_id integer not null
		constraint fk_rtintake_inventory references inventory,

	intake_date date not null
		constraint c_rtintake_1 check (intake_date <= CURRENT_DATE),
	comments_text varchar(255),

	status_code char(1) not null
		--I=Incomplete, C=Completed, V=Verified
		constraint c_rtintake_2 check (status_code in ('I','C','V')),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone,
	verify_by_id varchar(20) not null,
	verify_dtime timestamp(0) without time zone,
	version_nbr integer not null,
	constraint pk_rtintake primary key(xfreturn_id,inventory_id)
);

--Intake of items from transfer to inventory. The number of items taken into inventory
--must be equal to the number in the transfer transaction.
--NOTE: Returned items must reference inventory as the return of an item implies prior
--presence of the item in the inventory. This is not the case with intake of domnated
--items.
create table rtintake_item
(
	xfreturn_id integer not null,
	inventory_id integer not null,
	item_id integer not null,

	--Quantity/amount of usable/good item in inventory
	usable_qty decimal(12,2) not null
		constraint c_rtintake_item_1 check (usable_qty >= 0.00),
	location1_id integer --not null
		constraint fk_rtintake_item_location1 references location,
	
	--Quantity/amount of defective item in inventory
	defective_qty decimal(12,2) not null
		constraint c_rtintake_item_2 check (defective_qty >= 0.00),
	location2_id integer --not null
		constraint fk_rtintake_item_location2 references location,
	
	--Quantity/amount of expired item in inventory
	expired_qty decimal(12,2) not null
		constraint c_rtintake_item_3 check (defective_qty >= 0.00),
	location3_id integer --not null
		constraint fk_rtintake_item_location3 references location,

	--Units in which quantity of item is measured
	uom_code varchar(25) not null
		constraint fk_rtintake_item_unitofmeasure references unitofmeasure,

	status_code char(1) not null
		--P=Pending verification, V=Verified
		constraint c_rtintake_item_4 check (status_code in ('P','V')),
	comments_text varchar(255),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null,

	constraint fk_rtintake_item_intake foreign key (xfreturn_id,inventory_id) 
		references rtintake(inventory_id,xfreturn_id),
	constraint pk_rtintake_item primary key(xfreturn_id,inventory_id,item_id)
);
create index dk_rtintake_item_1 on rtintake_item(inventory_id, item_id);
create index dk_rtintake_item_2 on rtintake_item(item_id);

--
--Outposts/agencies receiving goods (from inventories) for distribution to citizens
--
create table agency
(
	agency_id integer not null generated by default as identity
		constraint pk_agency primary key,
	
	--TRN to ensure agency's authenticity and uniqueness. Verify if TRN capture is allowed.
	--trn_nbr integer not null
	--	constraint c_agency_1 check (trn_nbr between 19 and 99999999),
	
	agency_name varchar(120) not null
		--Agency name must be uppercase and unique
		constraint c_agency_2 check (agency_name = upper(agency_name))
		constraint uk_agency_1 unique,
	
	address1_text varchar(255) not null,
	address2_text varchar(255),
	--Indicate parish in which agency is located
	parish_code char(2) not null
		constraint fk_agency_parish references parish,
	
	contact_name varchar(50) not null
		--Contact name must be in upper case.
		constraint c_agency_3 check (contact_name = upper(contact_name)),
	phone_no varchar(20) not null,
	email_text varchar(100),
	
	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null
);

--
--Stores details of requests by agencies/shelters for relief supplies
--
create table reliefrqst
(
	reliefrqst_id integer not null generated by default as identity
		constraint pk_reliefrqst primary key,
	agency_id integer not null 
		constraint fk_reliefrqst_agency references agency,
	request_date date not null
		constraint c_reliefrqst_1 check (request_date <= CURRENT_DATE),
	urgency_ind char(1) not null
		--L=Low, M=Medium, H=High, C=Critical
		constraint c_reliefrqst_2 check (urgency_ind in ('L','M','H','C')),
	status_code smallint not null
		--0=Draft, 1=Awaiting approval, 2=Cancelled, 3=Submitted,
		--4=Denied, 5=Part filled, 6=Closed, 7=Filled
		constraint c_reliefrqst_3 check (status_code between 1 and 7),

	--Creates/Cancels request
	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,

	--Submits/Cancels request. Cancellation can be done by creator/reviewer
	review_by_id varchar(20)
		constraint c_reliefrqst_4a
		check ((review_by_id is null and status_code < 2)
			or (review_by_id is not null and status_code >= 2)),
	review_dtime timestamp(0) without time zone
		constraint c_reliefrqst_4b
		check ((review_by_id is null and review_dtime is null)
			or (review_by_id is not null and review_dtime is not null)),
	
	--Actions request - Fill, Part fill, Closes
	action_by_id varchar(20),
		constraint c_reliefrqst_5a
		check ((action_by_id is null and status_code < 4)
			or (action_by_id is not null and status_code >= 4)),
	action_dtime timestamp(0) without time zone,
		constraint c_reliefrqst_5b
		check ((action_by_id is null and action_dtime is null)
			or (action_by_id is not null and action_dtime is not null)),
	version_nbr integer not null
);
create index dk_reliefrqst_1 on reliefrqst(agency_id,request_date);
create index dk_reliefrqst_2 on reliefrqst(request_date,status_code);
create index dk_reliefrqst_3 on reliefrqst(status_code,urgency_ind);

create table reliefrqst_item
(
	reliefrqst_id integer not null
		constraint fk_reliefrqst_item_reliefrqst references reliefrqst,
	item_id integer not null
		constraint fk_reliefrqst_item_item references item,
	request_qty decimal(12,2) not null
		constraint c_reliefrqst_item_1 check (request_qty > 0.00),
	issue_qty decimal(12,2) not null
		constraint c_reliefrqst_item_2 check (issue_qty <= request_qty),
	urgency_ind char(1) not null
		constraint c_reliefrqst_item_3 check (urgency_ind in ('L','M','H','C')),
	--Reason for requested item is required if urgency is above medium
	rqst_reason_desc varchar(255)
		constraint c_reliefrqst_item_4
		check ((rqst_reason_desc is not null)
			or (rqst_reason_desc is null and urgency_ind in ('L','M'))),
	required_by_date date
		constraint c_reliefrqst_item_5
		check ((required_by_date is not null)
			or (required_by_date is null and urgency_ind in ('L','M'))),
	status_code char(1) not null
			--R=Requested, U=Unavailable, W=Waiting availability,
			--'D'=Denied, P=Partly filled, L=Limit allowed, F=Filled
		constraint c_reliefrqst_item_6
		check (status_code in ('R','U','W','D','P','L','F')),
	status_reason_desc varchar(255),
	action_by_id varchar(20)
		constraint c_reliefrqst_item_7
		check ((action_by_id is null and status_code = 'R') 
			or (action_by_id is not null and status_code != 'R')),
	action_dtime timestamp(0) without time zone
		constraint c_reliefrqst_item_8
		check ((action_by_id is null and action_dtime is null) 
			or (action_by_id is not null and action_dtime is not null)),
	version_nbr integer not null
);

--Assumption: Only usable items will be distributed. The quantity available for distribution is
--the item's usable quantity minus the reserved quantity. Verification of a distribution must reduce
--the usable quantity by the quantity distributed, and increment the reserved quantity by the same
--quantity.

--
--Record of distributions of items to distribution sites for pickup by citizens
--
create table reliefpkg
(
	reliefpkg_id integer not null generated by default as identity
		constraint pk_reliefpkg primary key,
	to_inventory_id integer not null
		constraint fk_reliefpkg_inventory references inventory,
	reliefrqst_id integer not null
		constraint fk_reliefpkg_reliefrqst references reliefrqst,

	--Date on which packaging started
	start_date date not null default CURRENT_DATE
		constraint c_reliefpkg_1 check (start_date <= CURRENT_DATE),

	--Date on which package was dispatched.
	dispatch_dtime timestamp(0) without time zone
		constraint c_reliefpkg_2
		check ((dispatch_dtime is null and status_code != 'D')
			or (dispatch_dtime is null and status_code = 'D')),

	--Mode(s) of transport for package from source inventories
	transport_mode varchar(255);

	comments_text varchar(255),

	status_code char(1) not null
		--Status of reliefpkg transaction: P=Processing, C=Completed, V=Verified, D=Dispatched
		constraint c_reliefpkg_3 check (status_code in ('P','C','V','D')),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone,
	verify_by_id varchar(20) not null,
	verify_dtime timestamp(0) without time zone,
	version_nbr integer not null
);
--Indexes to retrieve reliefpkg by date, source and destination Inventories
create index dk_reliefpkg_1 on reliefpkg(start_date);
create index dk_reliefpkg_3 on reliefpkg(to_inventory_id);

create table reliefpkg_item
(
	reliefpkg_id integer not null
		constraint fk_reliefpkg_item_reliefpkg references reliefpkg,
	--Inventory from which items are to be distributed
	fr_inventory_id integer not null,
	item_id integer not null,

	--Quantity/amount of item distributed
	item_qty decimal(12,2) not null
		constraint c_reliefpkg_item_1 check (item_qty >= 0.00),

	--Units in which quantity of item is measured
	uom_code varchar(25) not null
		constraint fk_reliefpkg_item_unitofmeasure references unitofmeasure,

	reason_text varchar(255),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null,
	constraint fk_reliefpkg_item_inventory foreign key(item_id, fr_inventory_id)
		references inventory(item_id, inventory_id),
	constraint pk_reliefpkg_item primary key(reliefpkg_id,fr_inventory_id,item_id)
);
create index dk_reliefpkg_item_1 on reliefpkg_item(fr_inventory_id,item_id);
create index dk_reliefpkg_item_2 on reliefpkg_item(item_id);

--
--Record of intake of items distributed to inventory
--During intake, items are inspected and classified as usable/defective
--and assigned to required locations.
--
create table dbintake
(
	reliefpkg_id integer not null
		constraint fk_dbintake_reliefpkg references reliefpkg,

	inventory_id integer not null
		constraint fk_dbintake_inventory references inventory,

	intake_date date not null
		constraint c_dbintake_1 check (intake_date <= CURRENT_DATE),
	comments_text varchar(255),

	status_code char(1) not null
		--I=Incomplete, C=Completed, V=Verified
		constraint c_dbintake_2 check (status_code in ('I','C','V')),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone,
	verify_by_id varchar(20) not null,
	verify_dtime timestamp(0) without time zone,

--NOTE: Intake of items must not reference inventory as items being taken to the
--inventory may not yet exist in it.	version_nbr integer not null
	constraint pk_dbintake primary key(reliefpkg_id,inventory_id)
);

--Intake of items from distributed to inventory. The number of items taken into inventory
--must be equal to the number in the reliefpkg transaction. Assignment of items to
--locations is optional.
--NOTE: Intake of items from a reliefpkg must not reference inventory as items being
--taken to the inventory may not yet exist in it.

create table dbintake_item
(
	reliefpkg_id integer not null,
	inventory_id integer not null,
	item_id integer not null,

	--Quantity/amount of usable/good item in inventory
	usable_qty decimal(12,2) not null
		constraint c_dbintake_item_1 check (usable_qty >= 0.00),
	location1_id integer --not null
		constraint fk_dbintake_item_location1 references location,
	
	--Quantity/amount of defective item in inventory
	defective_qty decimal(12,2) not null
		constraint c_dbintake_item_2 check (defective_qty >= 0.00),
	location2_id integer --not null
		constraint fk_dbintake_item_location2 references location,
	
	--Quantity/amount of expired item in inventory
	expired_qty decimal(12,2) not null
		constraint c_dbintake_item_3 check (defective_qty >= 0.00),
	location3_id integer --not null
		constraint fk_dbintake_item_location3 references location,

	--Units in which quantity of item is measured
	uom_code varchar(25) not null
		constraint fk_dbintake_item_unitofmeasure references unitofmeasure,

	status_code char(1) not null
		--P=Pending verification, V=Verified
		constraint c_dbintake_item_4 check (status_code in ('P','V')),
	comments_text varchar(255),

	create_by_id varchar(20) not null,
	create_dtime timestamp(0) without time zone not null,
	update_by_id varchar(20) not null,
	update_dtime timestamp(0) without time zone not null,
	version_nbr integer not null,

	constraint fk_dbintake_item_intake foreign key (reliefpkg_id,inventory_id) 
		references dbintake(reliefpkg_id,inventory_id),
	constraint pk_dbintake_item primary key(reliefpkg_id,inventory_id,item_id)
);
create index dk_dbintake_item_1 on dbintake_item(inventory_id, item_id);
create index dk_dbintake_item_2 on dbintake_item(item_id);

--%%%Create tables for item reliefpkg and receipt into distributor's inventory
