-- ============================================================================
-- Migration Script: Add itemcostdef Table
-- ============================================================================
-- Purpose: Create itemcostdef table to define cost types for items
--          (Purchase Price, CIF, Storage, Transport, Inspection, etc.)
--
-- Author: DMIS Development Team
-- Date: November 24, 2025
--
-- Dependencies:
--   - PostgreSQL citext extension
--
-- Safety Features:
--   - Transaction-based execution (all-or-nothing)
--   - Pre-migration validation checks
--   - Post-migration constraint verification
--   - No modifications to existing tables
--
-- ============================================================================

BEGIN;

-- ============================================================================
-- PRE-MIGRATION VALIDATION
-- ============================================================================

DO $$
DECLARE
    v_table_exists BOOLEAN;
    v_current_table_count INTEGER;
BEGIN
    -- Verify itemcostdef does not already exist
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'itemcostdef'
    ) INTO v_table_exists;
    
    IF v_table_exists THEN
        RAISE EXCEPTION 'Table itemcostdef already exists. Migration aborted.';
    END IF;
    
    -- Record current table count (should be 49)
    SELECT COUNT(*) INTO v_current_table_count
    FROM information_schema.tables
    WHERE table_schema = 'public' 
    AND table_type = 'BASE TABLE';
    
    RAISE NOTICE 'Pre-migration validation passed';
    RAISE NOTICE 'Current table count: %', v_current_table_count;
END $$;

-- ============================================================================
-- EXTENSION SETUP
-- ============================================================================

-- Ensure citext extension exists for case-insensitive text columns
CREATE EXTENSION IF NOT EXISTS citext;

-- ============================================================================
-- TABLE CREATION
-- ============================================================================

CREATE TABLE itemcostdef
(
    cost_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_adnlitemcost PRIMARY KEY,

    -- Name of cost e.g. Purchase Price, CIF, Storage, Transport, Inspection,
    -- Intake, Warehousing, etc.
    cost_name citext NOT NULL
        CONSTRAINT c_itemcostdef_1 CHECK (length(cost_name) <= 50)
        CONSTRAINT uk_itemcostdef_1 UNIQUE,

    -- Example: Labor costs for unloading shipments, checking for damage, verifying
    -- quantity, and routing the items to storage.
    cost_desc VARCHAR(255) NOT NULL,

    -- Type of cost - Purchase cost, Additional cost. Provide dropdown list for selection.
    cost_type CHAR(16) NOT NULL
        CONSTRAINT c_itemcostdef_2 CHECK (cost_type IN ('PURCHASE','ADDITIONAL')),
    
    status_code CHAR(1) NOT NULL
        -- A=Active, I=Inactive
        CONSTRAINT c_itemcostdef_3 CHECK (status_code IN ('A','I')),

    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Index on cost_type for filtering by purchase/additional costs
CREATE INDEX idx_itemcostdef_type ON itemcostdef(cost_type);

-- Index on status_code for filtering active/inactive costs
CREATE INDEX idx_itemcostdef_status ON itemcostdef(status_code);

-- ============================================================================
-- POST-MIGRATION VALIDATION
-- ============================================================================

DO $$
DECLARE
    v_table_exists BOOLEAN;
    v_pk_exists BOOLEAN;
    v_uk_exists BOOLEAN;
    v_check1_exists BOOLEAN;
    v_check2_exists BOOLEAN;
    v_check3_exists BOOLEAN;
    v_idx_type_exists BOOLEAN;
    v_idx_status_exists BOOLEAN;
    v_new_table_count INTEGER;
    v_column_count INTEGER;
BEGIN
    -- Verify table was created
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'itemcostdef'
    ) INTO v_table_exists;
    
    IF NOT v_table_exists THEN
        RAISE EXCEPTION 'Table itemcostdef was not created. Migration failed.';
    END IF;
    
    -- Verify primary key constraint
    SELECT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conrelid = 'itemcostdef'::regclass 
        AND contype = 'p'
        AND conname = 'pk_adnlitemcost'
    ) INTO v_pk_exists;
    
    IF NOT v_pk_exists THEN
        RAISE EXCEPTION 'Primary key pk_adnlitemcost not found. Migration failed.';
    END IF;
    
    -- Verify unique constraint
    SELECT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conrelid = 'itemcostdef'::regclass 
        AND contype = 'u'
        AND conname = 'uk_itemcostdef_1'
    ) INTO v_uk_exists;
    
    IF NOT v_uk_exists THEN
        RAISE EXCEPTION 'Unique constraint uk_itemcostdef_1 not found. Migration failed.';
    END IF;
    
    -- Verify CHECK constraints
    SELECT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conrelid = 'itemcostdef'::regclass 
        AND contype = 'c'
        AND conname = 'c_itemcostdef_1'
    ) INTO v_check1_exists;
    
    SELECT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conrelid = 'itemcostdef'::regclass 
        AND contype = 'c'
        AND conname = 'c_itemcostdef_2'
    ) INTO v_check2_exists;
    
    SELECT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conrelid = 'itemcostdef'::regclass 
        AND contype = 'c'
        AND conname = 'c_itemcostdef_3'
    ) INTO v_check3_exists;
    
    IF NOT (v_check1_exists AND v_check2_exists AND v_check3_exists) THEN
        RAISE EXCEPTION 'CHECK constraints not found. Migration failed.';
    END IF;
    
    -- Verify indexes
    SELECT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE tablename = 'itemcostdef' 
        AND indexname = 'idx_itemcostdef_type'
    ) INTO v_idx_type_exists;
    
    SELECT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE tablename = 'itemcostdef' 
        AND indexname = 'idx_itemcostdef_status'
    ) INTO v_idx_status_exists;
    
    IF NOT (v_idx_type_exists AND v_idx_status_exists) THEN
        RAISE EXCEPTION 'Indexes not created. Migration failed.';
    END IF;
    
    -- Verify column count (should be 10)
    SELECT COUNT(*) INTO v_column_count
    FROM information_schema.columns
    WHERE table_schema = 'public' 
    AND table_name = 'itemcostdef';
    
    IF v_column_count != 10 THEN
        RAISE EXCEPTION 'Expected 10 columns, found %. Migration failed.', v_column_count;
    END IF;
    
    -- Verify new table count (should be 50)
    SELECT COUNT(*) INTO v_new_table_count
    FROM information_schema.tables
    WHERE table_schema = 'public' 
    AND table_type = 'BASE TABLE';
    
    RAISE NOTICE '============================================================';
    RAISE NOTICE 'Post-migration validation passed';
    RAISE NOTICE 'New table count: %', v_new_table_count;
    RAISE NOTICE 'Columns in itemcostdef: %', v_column_count;
    RAISE NOTICE 'All constraints verified';
    RAISE NOTICE 'All indexes verified';
    RAISE NOTICE '============================================================';
    RAISE NOTICE 'Migration completed successfully';
    RAISE NOTICE 'Table: itemcostdef';
    RAISE NOTICE 'Total tables: 50 (was 49)';
    RAISE NOTICE 'Status: READY FOR USE';
    RAISE NOTICE '============================================================';
END $$;

COMMIT;
