-- ============================================================================
-- DRIMS - Item Category Table Schema Migration
-- ============================================================================
-- Purpose: Update itemcatg table structure to use category_id as identity PK
--          instead of category_code, while preserving foreign key references
--
-- Current State: 
--   - PK: category_code (varchar 30)
--   - FK from item.category_code → itemcatg.category_code
--   - No category_id column
--   - No status_code column
--
-- Target State:
--   - PK: category_id (integer identity) with constraint pk_itemcatg
--   - category_code: varchar(30) unique with uppercase check
--   - status_code: char(1) with check constraint
--   - FK from item.category_id → itemcatg.category_id
--
-- Prerequisites: itemcatg table must be empty
-- ============================================================================

BEGIN;

-- ============================================================================
-- SECTION 1: Capture Existing Foreign Key References
-- ============================================================================

-- Current FK: item.category_code → itemcatg.category_code
-- Note: This will be dropped and recreated as item.category_id → itemcatg.category_id

-- Check that itemcatg is empty (safety check)
DO $$
DECLARE
    row_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO row_count FROM itemcatg;
    IF row_count > 0 THEN
        RAISE EXCEPTION 'Migration aborted: itemcatg table is not empty (% rows found)', row_count;
    END IF;
END $$;

-- ============================================================================
-- SECTION 2: Drop Foreign Key from item table
-- ============================================================================

ALTER TABLE item DROP CONSTRAINT IF EXISTS item_category_code_fkey;

-- ============================================================================
-- SECTION 3: Drop and Recreate itemcatg Table
-- ============================================================================

-- Drop the existing itemcatg table
DROP TABLE IF EXISTS itemcatg CASCADE;

-- Recreate itemcatg with new schema
CREATE TABLE itemcatg 
(
    category_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_itemcatg PRIMARY KEY,

    category_code VARCHAR(30) NOT NULL
        CONSTRAINT c_itemcatg_1 CHECK (category_code = UPPER(category_code))
        CONSTRAINT uk_itemcatg_1 UNIQUE,

    -- Description of item category
    category_desc VARCHAR(60) NOT NULL,

    -- Any comments related to this item type
    comments_text TEXT,

    status_code CHAR(1) NOT NULL
        CONSTRAINT c_itemcatg_2 CHECK (status_code IN ('A','I')),

    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);

-- Add comment on table
COMMENT ON TABLE itemcatg IS 'Item Category master data table - defines categories for relief items';

-- Add column comments
COMMENT ON COLUMN itemcatg.category_id IS 'Primary key - auto-generated category identifier';
COMMENT ON COLUMN itemcatg.category_code IS 'Unique category code (uppercase) - business key';
COMMENT ON COLUMN itemcatg.category_desc IS 'Description of the item category';
COMMENT ON COLUMN itemcatg.comments_text IS 'Additional comments or notes about this category';
COMMENT ON COLUMN itemcatg.status_code IS 'Status: A=Active, I=Inactive';
COMMENT ON COLUMN itemcatg.version_nbr IS 'Optimistic locking version number';

-- ============================================================================
-- SECTION 4: Update item table to use category_id
-- ============================================================================

-- Check if item.category_id column already exists
DO $$
BEGIN
    -- Add category_id column to item table if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'item' AND column_name = 'category_id'
    ) THEN
        ALTER TABLE item ADD COLUMN category_id INTEGER;
        
        RAISE NOTICE 'Added category_id column to item table';
    END IF;
END $$;

-- Note: Since both tables are empty, we don't need to migrate data
-- The category_code column in item table can remain for legacy compatibility
-- or be removed in a future migration if no longer needed

-- ============================================================================
-- SECTION 5: Recreate Foreign Key Constraint
-- ============================================================================

-- Create FK from item.category_id to itemcatg.category_id
-- Using the same ON DELETE/ON UPDATE rules as before (NO ACTION)
ALTER TABLE item 
    ADD CONSTRAINT item_category_id_fkey 
    FOREIGN KEY (category_id) 
    REFERENCES itemcatg(category_id)
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION;

-- ============================================================================
-- SECTION 6: Create Indexes
-- ============================================================================

-- The unique constraint uk_itemcatg_1 on category_code automatically creates an index
-- The primary key pk_itemcatg on category_id automatically creates an index
-- No additional indexes needed at this time

-- Create index on status_code for filtering active categories
CREATE INDEX idx_itemcatg_status_code ON itemcatg(status_code);

-- ============================================================================
-- SECTION 7: Verification
-- ============================================================================

-- Verify the new structure
DO $$
DECLARE
    v_pk_name TEXT;
    v_uk_name TEXT;
    v_check2_name INTEGER;
    v_fk_name TEXT;
BEGIN
    -- Check primary key constraint
    SELECT conname INTO v_pk_name
    FROM pg_constraint
    WHERE conrelid = 'itemcatg'::regclass 
      AND contype = 'p';
    
    IF v_pk_name != 'pk_itemcatg' THEN
        RAISE EXCEPTION 'Primary key constraint not found or incorrectly named: %', v_pk_name;
    END IF;
    
    -- Check unique constraint
    SELECT conname INTO v_uk_name
    FROM pg_constraint
    WHERE conrelid = 'itemcatg'::regclass 
      AND contype = 'u';
    
    IF v_uk_name != 'uk_itemcatg_1' THEN
        RAISE EXCEPTION 'Unique constraint not found or incorrectly named: %', v_uk_name;
    END IF;
    
    -- Check check constraints exist
    SELECT COUNT(*) INTO v_check2_name
    FROM pg_constraint
    WHERE conrelid = 'itemcatg'::regclass 
      AND contype = 'c'
      AND conname IN ('c_itemcatg_1', 'c_itemcatg_2');
    
    IF v_check2_name != 2 THEN
        RAISE EXCEPTION 'Check constraints not found (expected 2, found %)', v_check2_name;
    END IF;
    
    -- Check foreign key from item table
    SELECT conname INTO v_fk_name
    FROM pg_constraint
    WHERE conrelid = 'item'::regclass 
      AND contype = 'f'
      AND conname = 'item_category_id_fkey';
    
    IF v_fk_name IS NULL THEN
        RAISE EXCEPTION 'Foreign key constraint item_category_id_fkey not found';
    END IF;
    
    RAISE NOTICE '✓ All constraints verified successfully';
    RAISE NOTICE '  - Primary key: pk_itemcatg on category_id';
    RAISE NOTICE '  - Unique constraint: uk_itemcatg_1 on category_code';
    RAISE NOTICE '  - Check constraints: c_itemcatg_1 (uppercase), c_itemcatg_2 (status)';
    RAISE NOTICE '  - Foreign key: item_category_id_fkey (item.category_id → itemcatg.category_id)';
END $$;

COMMIT;

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Summary:
-- ✓ itemcatg table recreated with category_id as identity PK
-- ✓ category_code is now a unique column with uppercase check
-- ✓ status_code column added with check constraint
-- ✓ All audit fields present (create_by_id, create_dtime, update_by_id, update_dtime, version_nbr)
-- ✓ Foreign key from item.category_id to itemcatg.category_id recreated
-- ✓ Indexes created on status_code for performance
-- ✓ All constraint names match requirements
-- ============================================================================
